config/routes.rb
DemoApp::Application.routes.draw do
  get 'sessions/new'
  get 'sessions/new'
  get 'users/new'
  root 'page#index'
  get 'page_about_us'   => 'page#page_about_us'
  get 'contact' => 'page#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'forms'  => 'users#forms'
  get 'indoorsheet'  => 'users#indoorsheet'
  get 'indoorpaper'  => 'users#indoorpaper'
  get 'opdcasepaper'  => 'users#opdcasepaper'
  get 'doctors'  => 'page#doctors'
  get 'doctor' => 'users#doctor'
  get 'search'  => 'users#search'
  get 'tips'  => 'page#tips'
  get 'fitness'  => 'page#fitness'
  get 'beauty'  => 'page#beauty'
  get 'diseases_and_conditions'  => 'page#diseases_and_conditions'
  get 'pregnancy'  => 'page#pregnancy'
  get 'parenting'  => 'page#parenting'
    get 'weight_loss'  => 'page#weight_loss'
    get 'yoga'  => 'page#yoga'
    get 'diet'  => 'page#diet'


  resources :users









  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
 	has_secure_password
 	validates :password, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def forms
    end

    def indoorsheet
    end
def indoorpaper
    end
     def opdcasepaper
    end
    def doctor
    end
    def search
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/create.html.erb
def create
  # some object you want to create
  # if the object.save is fine
  #   redirect_to object
  # else
  #   render new with the errors
  # end
end

app/views/users/doctor.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Doctor Registration</h4></center></div><br>
<%= form_for :article do |f| %>
<div class="container">
<div class="row">
<div class="col-md-6">
<%= f.label :Name %>
    <%= f.text_field :Name %>
</div>
<div class="col-md-6">
<%= f.label :Doctor_ID  %>
    <%= f.text_field :Doctor_ID %>
</div>
</div>

<div class="row">
<div class="col-md-6">
<%= f.label :Age %>
    <%= f.text_field:Age %>
</div>
<div class="col-md-6">
<%= f.label :Gender %>
    <%= f.text_field:Gender %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Birth_date %>
<%= f.text_field:Birth_date %>
</div>
<div class="col-md-6">
<%= f.label :Address  %>
    <%= f.text_area:Address %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Occupation %>
    <%= f.text_field:Occupation %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :User_Name  %>
    <%= f.text_field:User_Name %>
</div>

</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Password  %>
    <%= f.text_field:Password %>
</div>

</div>

<div class="row">
<div class="col-md-6">
<%= f.label :Email_ID  %>
    <%= f.text_field:Email_ID %>
</div>

</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Phone_No  %>
    <%= f.text_field:Phone_No %>
</div>

</div>

    <center><%= f.submit %></center>
  </div>
<% end %>
  
 
</div>

app/views/users/forms.html.erb
<h1>Welcome...</h1>
 <center><%= link_to "Indoor Sheet", indoorsheet_path, class: "btn btn-lg btn-primary" %><br><br>

<%= link_to "Indoor Paper", indoorpaper_path, class: "btn btn-lg btn-primary" %><br><br>
<%= link_to "OPD Case Paper", opdcasepaper_path, class: "btn btn-lg btn-primary" %><br><br>

<%= link_to "Doctor", doctor_path, class: "btn btn-lg btn-primary" %><br><br>
<%= link_to "Search", search_path, class: "btn btn-lg btn-primary" %><br><br>
 </center>

app/views/users/indoor.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Indoor Cont Sheet</h4></center></div>
<div class="row">
  <div class="col-md-4 col-md-offset-3">
  <%= form_for :article do |f| %>
    <%= f.label :Case_No %>
    <%= f.text_field :Case_No %><br>
    <%= f.label :Patient_Name  %>
    <%= f.text_field :Patient_Name %>
    <%= f.label :Date  %>
    <%= f.text_field:Date %>
    <%= f.label :Time %>
    <%= f.text_field:Time %>
    <%= f.label :Doctors_Notes_and_Orders %>
    <%= f.text_area:Doctors_Notes_and_Orders %>
    <%= f.label :Nurses_Record  %><br>
        <%= f.label :Time %>
        <%= f.text_field:Time %>
        <%= f.label :TPR_B_P %>
  
        <%= f.text_field:TPR_B_P %>
            <%= f.text_area:DD %>

    <%= f.submit %>
  
<% end %>
  
  </div>
</div>

app/views/users/indoorpaper.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Indoor Paper</h4></center></div><br>
<%= form_for :article do |f| %>
<div class="container">
<div class="row">
<div class="col-md-6">
<%= f.label :Bill_No %>
    <%= f.text_field :Bill_No %>
</div>
<div class="col-md-6">
<%= f.label :Case_No %>
    <%= f.text_field :Case_No %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Patient_Name  %>
    <%= f.text_field :Patient_Name %>
</div>
<div class="col-md-6">
<%= f.label :Age %>
    <%= f.text_field:Age %>
</div>
</div> <h4>Address</h4>
<div class="row">
<div class="col-md-12">
<%= f.text_area:Address %>
</div>
</div>

<div class="row">
<div class="col-md-6">
<%= f.label :Diagnosis  %>
    <%= f.text_area:Diagnosis %>
</div>
<div class="col-md-6">
<%= f.label :Treatment %>
    <%= f.text_area:Treatment %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Surgeon_Name  %>
    <%= f.text_field:Surgeon_Name %>
</div>
<div class="col-md-6">
<%= f.label :Anansthesia_Surgeon%>
    <%= f.text_field:Anansthesia_Surgeon %>
</div>
</div>
  <div class="row">
<div class="col-md-6">
<%= f.label :Delivery  %>
    <%= f.text_field:Delivery %>
</div>
<div class="col-md-6">
    <%= f.text_area:Comment1 %>
</div>
</div> 
 <div class="row">
<div class="col-md-6">
<%= f.label :Anansthesia  %>
    <%= f.text_field:Anansthesia %>
</div>
<div class="col-md-6">
    <%= f.text_area:Comment2 %>
</div>
</div> 
<h1>Baby's Information</h1>
 <div class="row">
<div class="col-md-6">
<%= f.label :Birth_Date  %>
    <%= f.text_field:Birth_Date %>
</div>
<div class="col-md-6">
<%= f.label :Birth_Time  %>
    <%= f.text_field:Birth_Time %>
</div>
</div>
 <div class="row">
<div class="col-md-6">
<%= f.label :Weight  %>
    <%= f.text_field:Weight %>
</div>
<div class="col-md-6">
<%= f.label :Status  %>
    <%= f.text_field:Status %>
</div>
</div>
<div class="row">
<div class="col-md-6">
<%= f.label :Asphxia  %>
    <%= f.text_field:Asphxia %>
</div>
<div class="col-md-6">
<%= f.label :Gender  %>
    <%= f.text_field:Gender %>
</div>
</div>
    <center><%= f.submit %></center>
  </div>
<% end %>
  
 
</div>

app/views/users/indoorsheet.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Indoor Cont Sheet</h4></center></div><br>
<%= form_for :article do |f| %>
<div class="container">
<div class="row">
<div class="col-md-6">
<%= f.label :Case_No %>
    <%= f.text_field :Case_No %>
</div>
<div class="col-md-6">
<%= f.label :Patient_Name  %>
    <%= f.text_field :Patient_Name %>
</div>
</div>

<div class="row">
<div class="col-md-6">
<%= f.label :Date  %>
    <%= f.text_field:Date %>
</div>
<div class="col-md-6">
<%= f.label :Time %>
    <%= f.text_field:Time %>
</div>
</div> <h4>Doctors Notes and Orders</h4>
<div class="row">
<div class="col-md-12">
<%= f.text_area:Doctors_Notes_and_Orders %>
</div>
</div>
 <h4>Nurse Record</h4><br>
<div class="row">
<div class="col-md-6">
<%= f.label :Time  %>
    <%= f.text_field:N_Time %>
</div>
<div class="col-md-6">
<%= f.label :TPR_B_P %>
    <%= f.text_field:TPR_B_P %>
</div>

</div>
<div class="col-md-6">
<%= f.label :Cpmment_Here %>

  <%= f.text_area:comment %>
</div>
</div>

<div>
   
    <center><%= f.submit %></center>
  </div>
<% end %>
  
 
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/opd.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Indoor Cont Sheet</h4></center></div>
<div class="row">
  <div class="col-md-4 col-md-offset-3">
  <%= form_for :article do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
    <%= f.submit %>
  
<% end %>
  
  </div>
</div>

app/views/users/opdcasepaper.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>OPD Case Paper</h4></center></div><br>
<%= form_for :article do |f| %>
<div class="container">
<div class="row">
<div class="col-md-6">
<%= f.label :No %>
    <%= f.text_field :No %>
</div>
<div class="col-md-6">
<%= f.label :Date  %>
    <%= f.text_field :Date %>
</div>
</div>

<div class="row">
<div class="col-md-6">
<%= f.label :Name  %>
    <%= f.text_field:Name %>
</div>
<div class="col-md-6">
<%= f.label :Age %>
    <%= f.text_field:Age %>
</div>
</div> <div class="row">
<div class="col-md-6">
<%= f.label :Residence  %>
    <%= f.text_area:Residence %>
</div>
<div class="col-md-6">
<%= f.label :Present_Complaints %>
    <%= f.text_area:Present_Complaints %>
</div>
</div>
 

<div class="row">
<div class="col-md-4">
<%= f.label :PMC  %>
    <%= f.text_area:PMC %>
</div>
<div class="col-md-4">
<%= f.label :Pr_Mc %>
    <%= f.text_field:Pr_Mc %>
</div>
<div class="col-md-4">
<%= f.label :LMP %>
    <%= f.text_field:LMP %>
</div>
</div>



<div class="row">
<div class="col-md-12">
<%= f.label :OH  %>
    <%= f.text_field:OH %>
</div>
</div>

<h4>Past H/O</h4>
<div class="row">
<div class="col-md-6">
<%= f.label :Family_HO %>
    <%= f.text_area:Family_HO %>
</div>
<div class="col-md-6">
<%= f.label :Personal_HO %>
    <%= f.text_area:Personal_HO %>
</div>
</div>

<div class="row">
<div class="col-md-12">
<%= f.label :Clinical_Exam  %>
    <%= f.text_area:Clinical_Exam %>
</div>
</div>


<div class="row">
<div class="col-md-4">
<%= f.label :HB  %>
    <%= f.text_field:HB %>
</div>
<div class="col-md-4">
<%= f.label :CBC %>
    <%= f.text_field:CBC %>
</div>
<div class="col-md-4">
<%= f.label :B1_Gr %>
    <%= f.text_field:B1_Gr %>
</div>
</div>


<div class="row">
<div class="col-md-4">
<%= f.label :HBS_Ag  %>
    <%= f.text_field:HBS_Ag %>
</div>
<div class="col-md-4">
<%= f.label :HIV %>
    <%= f.text_field:HIV %>
</div>
<div class="col-md-4">
<%= f.label :INJ_TT_1st_2nd %>
    <%= f.text_field:INJ_TT_1st_2nd %>
</div>
</div>



<div class="row">
<div class="col-md-6">
<%= f.label :LMP %>
    <%= f.text_field:LMP %>
</div>
<div class="col-md-6">
<%= f.label :EDD %>
    <%= f.text_field:Personal_HO %>
</div>
</div>
    <center><%= f.submit %></center>
<% end %>
  
 
</div>

app/views/users/search.html.erb
<div><center><h1>Nitave Hospital</h1></center></div>
<center><div><h4>Search</h4></center></div><br>
<%= form_for :article do |f| %>
<div class="container">

Search From CasePaper:
<div class="row">
<div class="col-md-4">
<%= f.label :Name %>
    <%= f.text_field :CName %>
</div>
<div class="col-md-4">

</div>
<div class="col-md-4">
<%= link_to "Search", '#', class: "btn btn-lg btn-primary" %>

</div>
</div><br><br>


Search From Indoor Paper:
<div class="row">
<div class="col-md-4">
<%= f.label :Name %>
    <%= f.text_field :IPName %>
</div>
<div class="col-md-4">
<%= f.label :Case_No%>
    <%= f.text_field :IPCase_No %>
</div>
<div class="col-md-4">
<%= link_to "Search", '#', class: "btn btn-lg btn-primary" %>

</div>
</div><br><br>


Search From Indoor Sheet:
<div class="row">
<div class="col-md-4">
<%= f.label :Name %>
    <%= f.text_field :ISName %>
</div>
<div class="col-md-4">
<%= f.label :Case_No%>
    <%= f.text_field :ISCase_No %>
</div>
<div class="col-md-4">
<%= link_to "Search", '#', class: "btn btn-lg btn-primary" %>

</div>
</div><br><br>



Search Acording to Delivery Type:
<div class="row">
<div class="col-md-4">
<%= f.label :Type %>
    <%= f.text_field :DType %>
</div>
<div class="col-md-4">

</div>
<div class="col-md-4">
<%= link_to "Search", '#', class: "btn btn-lg btn-primary" %>

</div>
</div><br><br>


Search Acording to Date:
<div class="row">
<div class="col-md-4">
<%= f.label :Date%>
    <%= f.text_field :Date %>
</div>
<div class="col-md-4">

</div>
<div class="col-md-4">
<%= link_to "Search", '#', class: "btn btn-lg btn-primary" %>

</div>
</div><br><br>

<% end %>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>