config/routes.rb
DemoApp::Application.routes.draw do
  get 'sessions/new'
  get 'sessions/new'
  get 'users/new'
  root 'page#index'
  get 'page_about_us'   => 'page#page_about_us'
  get 'contact' => 'page#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'forms'  => 'users#forms'
  get 'indoorsheet'  => 'users#indoorsheet'
  get 'indoorpaper'  => 'users#indoorpaper'
  get 'opdcasepaper'  => 'users#opdcasepaper'
  get 'doctors'  => 'page#doctors'
  get 'doctor' => 'users#doctor'
  get 'search'  => 'users#search'
  get 'tips'  => 'page#tips'
  get 'fitness'  => 'page#fitness'
  get 'beauty'  => 'page#beauty'
  get 'diseases_and_conditions'  => 'page#diseases_and_conditions'
  get 'pregnancy'  => 'page#pregnancy'
  get 'parenting'  => 'page#parenting'
    get 'weight_loss'  => 'page#weight_loss'
    get 'yoga'  => 'page#yoga'
    get 'diet'  => 'page#diet'


  resources :users









  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/indoorpaper.rb
class Indoorpaper < ActiveRecord::Base
	
validates :Patient_Name, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }   
     validates :Age,  presence: true
    validates_length_of :Age,
          # shorter than 16 characters
   :in => 1..2         # between 8 
 validates :Bill_No,  presence: true
 validates :Case_No,  presence: true
  validates :Patient_Name, presence: true
	    validates :Diagnosis,  presence: true
	    	    validates :Treatment,  presence: true
validates :Surgeon_Name, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" } 
    validates :Anansthesia_Surgeon, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" } 
    validates :Weight,  presence: true
    validates_length_of :Weight,
          # shorter than 16 characters
   :in => 1..3
   validates :Status, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" } 
validates :Asphxia, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" } 
     validates :Gender,  presence: true



end

app/models/indoorsheet.rb
class Indoorsheet < ActiveRecord::Base
	
end

app/models/opd.rb
class Opd < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
 	has_secure_password
 	validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
def index
	@doctor=Doctor.all
end
def show
   
  end

  def new
    @doctor = Doctor.new
    #2.times do
     # @question = @survey.questions.build
    #end
  end
   def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      flash[:notice] = 'Successfully created'
      redirect_to show_path
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end
  private
  def doctor_params
    params.require(:doctor).permit(:Name, :Doctor_ID, :Age, :Gender, :Birth_date, :Address, :Occupation,:User_Name ,:Password,:Email_ID ,:Phone_No )
  end
end

app/controllers/opds_controller.rb
class OpdsController < ApplicationController
def index
	@opd=Opd.all
end
def show
   
  end

  def new
    @opd = Opd.new
    #2.times do
     # @question = @survey.questions.build
    #end
  end
   def create
    @opd = Opd.new(opd_params)
    if @opd.save
      flash[:notice] = 'Successfully created'
      redirect_to show_path
    else

      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end
  private
  def opd_params
    params.require(:opd).permit( :No, :Date, :Name, :Age, :Residence, :Present_Complaints, :PMC , :Pr_Mc, :LMP , :OH, :Family_HO, :Personal_HO, :Clinical_Exam, :HB, :CBC, :B1_Gr, :HBS_Ag , :HIV , :INJ_TT_1st_2nd, :LMP, :EDD) 
end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@title = "Index"
  end

  def contact
  	@title="Contact"
  end

  def page_about_us
  	@title="About"
  end
  def doctors
  	@title="Doctors"
  end

  def tips
  	@title="Tips"
  end
def fitness
  	@title="Fitness"
  end
  def beauty
  	@title="Beauty"
  end
  def diseases_and_conditions
  	@title="Diseases_and_conditions"
  end

  def pregnancy
  	@title="Pregnancy"
  end
  def parenting
  	@title="Parenting"
  end
  def weight_loss
    @title="weight_loss"
  end
  def yoga
    @title="yoga"
  end
  def diet
    @title="diet"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def forms
    end

    def indoorsheet
    end
def indoorpaper
    end
     def opdcasepaper
    end
    def doctor
    end
    def search
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/indoorpapers_helper.rb
module IndoorpapersHelper
end

app/helpers/indoorsheets_helper.rb
module IndoorsheetsHelper
end

app/helpers/opds_helper.rb
module OpdsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
   <nav>
    <ul>
      <li><%= link_to "About",   page_about_us_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Nitave Hospital", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Our Team", doctors_path %></li>
        
        <li><%= link_to "Tips", tips_path %></li>
       
        <% if logged_in? %>
          <li><%= link_to "Forms", forms_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>

<%= csrf_meta_tag %>
<%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<section class="round">
<%= yield %>
</section>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/page/contact.html.erb
<section class="contact">
				<div class="container">
					<div class="row">
							<div class="contact-caption clearfix">
								<div class="contact-heading text-center">
									<h1>Contact Us</h1>
								</div>

								<div class="col-md-5 contact-info text-left">
									<h3>Contact Information</h3>
									<div class="info-detail">
										<ul><li><i class="fa fa-calendar"></i><span>Monday - Friday:</span> 9:30 AM to 6:30 PM</li></ul>
										<ul><li><i class="fa fa-map-marker"></i><span>Address:</span> 123 Some Street , London, UK, CP 123</li></ul>
										<ul><li><i class="fa fa-phone"></i><span>Phone:</span> (032) 987-1235</li></ul>
										<ul><li><i class="fa fa-fax"></i><span>Fax:</span> (123) 984-1234</li></ul>
										<ul><li><i class="fa fa-envelope"></i><span>Email:</span> info@doctor.com</li></ul>
									</div>
								</div>


								<div class="col-md-6 col-md-offset-1 contact-form">
									<h3>Leave Us a Message</h3>

									<form class="form">
										<input class="name" type="text" placeholder="Name">
										<input class="email" type="email" placeholder="Email">
										<input class="phone" type="text" placeholder="Phone No:">
										<textarea class="message" name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea>
										<input class="submit-btn" type="submit" value="SUBMIT">
									</form>
								</div>

							</div>
					</div>
				</div>
			</section><!-- end of contact section -->

app/views/page/diet.html.erb
<h1>About Diet</h1>
<h4>Milk and dairy products</h4>
<p>
skimmed milk, yogurt/curd, buttermilk (chhaach), cottage cheese (paneer). These foods are high in calcium, protein and Vitamin B-12. Talk to your doctor about what to eat if you are lactose intolerant.</p><br>
<h4>Vegetables,fruits,Meat,fish and poultry</h4>
 <p>these provide vitamins, minerals and fibre.And also provide concentrated proteins. </p><br>
 <h4>Fats and oils</h4>
 <p>
 Ghee, butter, coconut milk and oil are high in saturated fats, which are not very healthy. Vanaspati oil is high in trans fats, which are as bad for you as saturated fats. A better source of fat is vegetable oils because these contain more unsaturated fat.
 </p>

app/views/page/doctors.html.erb
<section class="team" id="team">
				<div class="container">
					<div class="row">
						<div class="team-heading text-center">
							<h1>Our Team</h1>
							<h4>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</h4>
						</div><br>


						<div class="col-md-2 single-member col-sm-4">
							<div class="person">
							<%= image_tag "member1.jpg", :size => "170x170" %>

							</div>

							<div class="person-detail">
								<div class="arrow-bottom"></div>
								<h3>Dr. M. Weiner, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
						
						</div>

						<div class="col-md-2 single-member col-sm-4">

							<div class="person-detail">
								<div class="arrow-top"></div>
								<h3>Dr. Danielle, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
							<div class="person">
							<%= image_tag "member2.jpg", :size => "170x170" %>
							</div>
						</div>
						<div class="col-md-2 single-member col-sm-4">
							<div class="person">
							<%= image_tag "member3.jpg", :size => "170x170" %>
							</div>
							<div class="person-detail">
								<div class="arrow-bottom"></div>
								<h3>Dr. Caitlin, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
						</div>

						<div class="col-md-2 single-member col-sm-4">
							<div class="person-detail">
								<div class="arrow-top"></div>
								<h3>Dr. Joseph, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
							<div class="person">
							<%= image_tag "member4.jpg", :size => "170x170" %>
							</div>
						</div>

						<div class="col-md-2 single-member col-sm-4">
							<div class="person">
							<%= image_tag "member5.jpg", :size => "170x170" %>
							</div>

							<div class="person-detail">
								<div class="arrow-bottom"></div>
								<h3>Dr. Michael, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
						</div>

						<div class="col-md-2 single-member col-sm-4">

							<div class="person-detail">
								<div class="arrow-top"></div>
								<h3>Dr. Hasina, M.D.</h3>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, </p>
							</div>
							<div class="person">
							<%= image_tag "member6.jpg", :size => "170x170" %>
							</div>

						</div>
					</div>
				</div>
			</section><!-- end of team section -->

app/views/page/fitness.html.erb
<h1>Fitness Tips</h1>
<div>
<center><%= link_to "Weight Loss", weight_loss_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Yoga", yoga_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Diet", diet_path, class: "btn btn-lg btn-primary" %>
</center>
</div>

app/views/page/index.html.erb
<% provide(:title, "Index") %>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
<head>
  
</head>
  <body>
  <div>  <%= image_tag "baby.jpg", :size => "1140x400" %>
</div><br><br>
  


        <div class="container">
            <div class="row  fbox">
                <div class="col-lg-3">
                   
					<%= image_tag "health1.jpg", :size => "140x100" %>
				
                    <h3>Health Care</h3>
                       <p> 
                        Health care is the diagnosis, treatment, and prevention of disease, illness, injury, and other physical and mental impairments in human beings. 
                        </p>
                
                </div>
                
                <div class="col-lg-3">
                    <%= image_tag "baby1.jpg", :size => "140x100" %>
                    <h3>Baby Name</h3>
                    
                         <p>
                        <a href="http://www.babynamesdirect.com/indian-baby-names/">Baby Names</a>
                </p>
                      
                </div>
                
                <div class="col-lg-3">
                    <%= image_tag "bottle1.jpg", :size => "140x100" %>
                    <h3>User Articles</h3>
                     <div class="fbox">
                         <p>
                        Pregnancy articles and information on BellyBelly. Try our pregnancy calculator, read about pregnancy symptoms and find out what to expect during pregnancy.
                        <br>
                        <a href="http://www.bellybelly.com.au/pregnancy/">Pregnancy Articles</a>
                </p>
                </div>
                 </div>

                <div class="col-lg-3">
                   <%= image_tag "nipple.jpg", :size => "140x100" %>
                    <h3>Week By Week</h3>
                     <div class="fbox">
                         <p>
                       Take this time to nourish your body and your baby and prepare for each new day of pregnancy, childbirth and parenting. Lamaze seeks to serve you as a guide and a resource, and we'll be with you every step of the way.
                </p>
                </div>
                                    </div>

            </div>
        </div>
  </body>
</html>

app/views/page/page_about_us.html.erb
<section class="about text-center" id="about">
				<div class="container">
					<div class="row">
						<h1>About Us</h1>
						<h4>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</h4>

						<div class="col-md-4 col-sm-6">
							<div class="single-about-detail clearfix">
								<div class="about-img">
									<%= image_tag "item1.jpg", :size => "200x200" %>
								</div>

								<div class="about-details">
									<div class="pentagon-text">
										<h1>C</h1>
									</div>

									<h3>Children’s specialist</h3>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
								</div>
							</div>
						</div>

						<div class="col-md-4 col-sm-6">
							<div class="single-about-detail">
								<div class="about-img">
									<%= image_tag "item2.jpg", :size => "200x200" %>
								</div>

								<div class="about-details">
									<div class="pentagon-text">
										<h1>W</h1>
									</div>

									<h3>Children’s specialist</h3>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
								</div>
							</div>
						</div>


						<div class="col-md-4 col-sm-6">
							<div class="single-about-detail">
								<div class="about-img">
									<%= image_tag "item3.jpg", :size => "200x200" %>
								</div>

								<div class="about-details">
									<div class="pentagon-text">
										<h1>M</h1>
									</div>

									<h3>Children’s specialist</h3>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
								</div>
							</div>
						</div>

					</div>
				</div>
			</section><!-- end of about section -->

app/views/page/tips.html.erb
<center><h1>Tips</h1></center>

<div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-center">
        <li><%= link_to "Fitness", fitness_path %></li>
        <li><%= link_to "Beauty", beauty_path %></li>
        
        <li><%= link_to "Diseases and Conditions", diseases_and_conditions_path %></li>
          <li><%= link_to "Pregnancy", pregnancy_path %></li>
        
          <li><%= link_to "Parenting", parenting_path %></li>
        
      </ul>
    </nav>
  </div>

app/views/page/weight_loss.html.erb
<h1>About Weight loss</h1>
<p>
   Weight loss refers to losing weight by reducing the total body mass. This is usually done by following an exercise and diet regime and has many physical, social and psychological benefits. There are various crash/fad diets which claim to help people lose weight quickly but they are harmful because they eliminate certain nutrients resulting in decreased immunity.
</p>
<h3>Body Mass Index</h3>
<p>
   It is the measure of an individual's relative size with respect to his body mass and height.  It is used to measure if one's weight is healthy or not. It is the ratio of your body weight to the square of your height and its unit is kg/m2 . An individual is considered to be healthy and have an appropriate weight if his/her BMI is within 18.5 and 24.9. Nowadays there’s a greater tendency to measure a person’s body fat percentage which many believe is a more accurate indication of one’s health and well-being.
</p>
<h3>Basal Metabolic Rate</h3>
<p>
   Basal metabolic rate measures the metabolic rate of the body, in short it measures the amount of energy your body requires to carry out its daily functions. Calculating BMR is difficult and it is advisable to use ones available online. The result tell you the number of calories you  need to burn.
</p>

app/views/page/yoga.html.erb
<h1>About Yoga</h1>
<h3>Yoga Precautions During Pregnancy</h3>
<p>
For the first trimester, standing Yoga Poses are advised as this will help strengthen the legs, enhance circulation, generate energy, and may reduce leg cramps.</p>
<p>During the second and third trimester, you may reduce your time spent for practicing the Asanas to prevent fatigue and overwork. Instead focus more on breathing and meditation.</p>
<p>It is also not advised to practice from the tenth through the fourteenth week of Pregnancy since these are crucial times. Do not overstretch the abdomen; the emphasis of your twisting poses should be on the shoulders and the upper back and not on the abdomen. Avoid doing inversion.
</p>
<h3>Yoga Poses During Pregnancy</h3>
<ul>
    <li>Sukhasana</li>
  <li>Shoulder lifts</li>
    <li>Neck excersises</li>
    <li>Vajrasana with ujjay</li>
    <li>NadiShodhanPranayam</li>
   <li> Meditation</li>

</ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>